
title: 我的个人空间
description: 摄影、股市文章与电子书
url: ""
baseurl: ""

markdown: kramdown
permalink: /blog/:title/

collections:
  photos:
    output: true
    permalink: /photos/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
  - scope:
      path: ""
      type: photos
    values:
      layout: article
